name: Makefile CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: apt update

    - name: Install deps
      run: apt install --assume-yes luajit lua-socket lua-lpeg

    - name: Run check
      run: make check

    - name: Run make README
      run: make README.md

